[package]
name = "tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.byte-slab-derive]
path = "../byte-slab-derive"

[dependencies.byte-slab]
path = "../byte-slab"
