[package]
name = "anachro-qspi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-slab = "0.1.1"
nrf52840-hal = "0.14.0"
cassette = "0.2.3"
defmt = "0.3.0"
